### ISSUE TITLE
issues/comments

### ISSUE THREAD

**Issue by bradh352** [snhilde/gator_hash_table#1]
This is what I've come up with from a cursory glance, I haven't tried compiling or running through ASAN or Valgrind to look for issues...

https://github.com/snhilde/gator_hash_table/blob/7099f5543f049406fb726290fb4601001d38b765/hash_table.c#L19

Bad form, should always use sizeof(*var) to safeguard future type replacement.

https://github.com/snhilde/gator_hash_table/blob/7099f5543f049406fb726290fb4601001d38b765/hash_table.c#L23

Missing +1 for NULL term, and maybe a bit pedantic assuming that CHAR_BIT might != 8. Might make more sense to just use strdup().

https://github.com/snhilde/gator_hash_table/blob/7099f5543f049406fb726290fb4601001d38b765/hash_table.c#L28

Missing +1 for NULL term, and maybe a bit pedantic assuming that CHAR_BIT might != 8. Might make more sense to just use strdup().

https://github.com/snhilde/gator_hash_table/blob/7099f5543f049406fb726290fb4601001d38b765/hash_table.c#L153

Missing +1 for NULL term, and maybe a bit pedantic assuming that CHAR_BIT might != 8. Might make more sense to just use strdup().

https://github.com/snhilde/gator_hash_table/blob/7099f5543f049406fb726290fb4601001d38b765/hash_table.c#L47

Should multiply by capacity or will have issues when capacity != 1.  Also, bad form as previously explained.

https://github.com/snhilde/gator_hash_table/blob/7099f5543f049406fb726290fb4601001d38b765/hash_table.h#L5

TABLE_SIZE doesn't make sense to be in a public header, also it appears to only be used in enumeration when really "capacity" should be used from the internal table structure.

https://github.com/snhilde/gator_hash_table/blob/7099f5543f049406fb726290fb4601001d38b765/hash_table.h#L10

Are you allowing the user to actually modify the return of "lookup"?  If not, it needs to return "const"

https://github.com/snhilde/gator_hash_table/blob/7099f5543f049406fb726290fb4601001d38b765/hash_table.h#L6-L13

In general, if something is public, it should be namespaced to prevent collisions with other public functions.  E.g.  hashtable_create(), hashtable_insert(), hashtable_get().  Also, its often helpful to put parameter names in the public prototypes as a form of documentation to allow other users to infer the proper usage of your functions.

https://github.com/snhilde/gator_hash_table/blob/7099f5543f049406fb726290fb4601001d38b765/hash_table.c#L112

Its typically considered bad form to use just   if(strcmp(...))  ... as it isn't obvious that you're checking that the 2 values are NOT EQUAL.  better form is   if (strcmp(..) != 0)  

https://github.com/snhilde/gator_hash_table/blob/7099f5543f049406fb726290fb4601001d38b765/hash_table.c#L133

Whew, this is actually a bit hard to read.  It looks like you tried to use referencing to save a couple lines of code rather than make it more readable. Though it will work, readability/auditability always wins.  Also, wouldn't it just be easier to pop it onto the *front* of the list rather than the tail?  It helps keep O(1) insertions.

https://github.com/snhilde/gator_hash_table/blob/7099f5543f049406fb726290fb4601001d38b765/hash_table.c#L139-L140

There are a lot of internal-use-only prototypes that aren't declared 'static' that probably should be to keep the global namespace clean.

**Comment by snhilde** [comment]
Thanks for taking the time to go through this. This is exactly the kind of feedback I am looking forward to.
