### ISSUE TITLE
Confusing formatting

### ISSUE THREAD

**Issue by user-none** [snhilde/gator_hash_table#2]
https://github.com/snhilde/gator_hash_table/blob/622c972d0de5f5ae3796116e171465394ca8a018/hash_table.c#L63-L69

This is really hard to read and confusing. The closing `}` is for the second for loop but it's indented so it looks like it's closing the sencond `if` statement.

You really should contain blocks in `{...}` when the logic applies to multiple lines. Even though the behavior of a `for` loop (and others) is to apply to the next line, it's better to easily see what applies where instead of having to think about it. Currently you have to go line by line through to determine the block. If the indentation is off (as it is in one place) it's even harder to understand the logic.

A good convention is to use `() {...}` for logic that spans multiple lines and `()` for next line only not another possible compound next line. For example, your `if` statements are fine without brackets.

**Comment by snhilde** [comment]
Changes made. Thanks for the feedback.
